/**
 * Redux Action types
 */
export enum ActionTypes {
  // Single Axis Control
  ZONE_STATE_CHANGE_REQ = 'ZONE_STATE_CHANGE_REQ',
  ZONE_GET_INFO = 'ZONE_GET_INFO',
  INITIAL_REDIS_SUBSCRIBER = 'INITIAL_REDIS_SUBSCRIBER',

  ZONE_COMMAND_ONLINE = 'ZONE_COMMAND_ONLINE',
  ZONE_COMMAND_SERVO_ON = 'ZONE_COMMAND_SERVO_ON',
  ZONE_COMMAND_SERVO_ON_ALL = 'ZONE_COMMAND_SERVO_ON_ALL',
  ZONE_COMMAND_AUTO = 'ZONE_COMMAND_AUTO',
  ZONE_COMMAND_OFFLINE = 'ZONE_COMMAND_OFFLINE',
  ZONE_COMMAND_SERVO_OFF = 'ZONE_COMMAND_SERVO_OFF',
  ZONE_COMMAND_SERVO_OFF_ALL = 'ZONE_COMMAND_SERVO_OFF_ALL',
  ZONE_COMMAND_MANUAL = 'ZONE_COMMAND_MANUAL',
  ZONE_COMMAND_SET_LIMIT = 'ZONE_COMMAND_SET_LIMIT',
  ZONE_COMMAND_CLEAR_LIMIT = 'ZONE_COMMAND_CLEAR_LIMIT',
  ZONE_COMMAND_DEFAULT_DESTNATION = 'ZONE_COMMAND_DEFAULT_DESTNATION',

  ZONE_COMMAND_HOME = 'ZONE_COMMAND_HOME',
  ZONE_COMMAND_HOME_ALL = 'ZONE_COMMAND_HOME_ALL',
  ZONE_COMMAND_RESET = 'ZONE_COMMAND_RESET',
  ZONE_COMMAND_RESET_ALL = 'ZONE_COMMAND_RESET_ALL',
  ZONE_COMMAND_MOVE = 'ZONE_COMMAND_MOVE',
  ZONE_COMMAND_MOVE_REL = 'ZONE_COMMAND_MOVE_REL',
  ZONE_COMMAND_ALL_MOVE_VEL = 'ZONE_COMMAND_ALL_MOVE_VEL',
  ZONE_COMMAND_STOP = 'ZONE_COMMAND_STOP',
  ZONE_COMMAND_STOP_ALL = 'ZONE_COMMAND_STOP_ALL',
  ZONE_CLEAR_MOTOR_ERROR_ALL = 'ZONE_CLEAR_MOTOR_ERROR_ALL',
  ZONE_COMMAND_DIRECTION_CHANGE = 'ZONE_COMMAND_DIRECTION_CHANGE',

  GROUP_COMMAND_ONLINE = 'GROUP_COMMAND_ONLINE',
  GROUP_COMMAND_OFFLINE = 'GROUP_COMMAND_OFFLINE',

  IOPORT_COMMAND_ONLINE = 'IOPORT_COMMAND_ONLINE',
  IOPORT_COMMAND_OFFLINE = 'IOPORT_COMMAND_OFFLINE',

  // Transfer Control
  ZONE_COMMAND_CHANGE_DESTINATION = 'ZONE_COMMAND_CHANGE_DESTINATION',
  ZONE_COMMAND_REVERSE_CHANGE_DESTINATION = 'ZONE_COMMAND_REVERSE_CHANGE_DESTINATION',
  ZONE_COMMAND_REORDER = 'ZONE_COMMAND_REORDER',
  ZONE_COMMAND_RECOVERY_ALL = 'ZONE_COMMAND_RECOVERY_ALL',
  ZONE_COMMAND_REINSTALL = 'ZONE_COMMAND_REINSTALL',
  ZONE_COMMAND_CHANGE_LOCATION = 'ZONE_COMMAND_CHANGE_LOCATION',
  ZONE_COMMAND_FORCE_RESERVE = 'ZONE_COMMAND_FORCE_RESERVE',
  ZONE_COMMAND_RESUME_ALL = 'ZONE_COMMAND_RESUME_ALL',
  ZONE_COMMAND_PAUSE_ALL = 'ZONE_COMMAND_PAUSE_ALL',
  COMMAND_SET_SAFE_LOCK = 'COMMAND_SET_SAFE_LOCK',

  // Zone Info
  ZONE_UPDATE = 'ZONE_UPDATE',
  ZONE_OCCUIED_UPDATE = 'ZONE_OCCUIED_UPDATE',
  // Select
  SELECT_TCM = 'SELECTED_TCM',
  SELECT_ZONE = 'SELECT_ZONE',
  SELECT_CCTV = 'SELECT_CCTV',
  SELECT_TASK = 'SELECT_TASK',
  SELECT_DESTNI = 'SELECT_DESTNI',
  SELECT_NEWLOCATION = 'SELECT_NEWLOCATION',
  SELECT_CLEAR = 'SELECT_CLEAR',
  ADD_ZONE_JUNCTION = 'ADD_ZONE_JUNCTION',

  // Task Info
  CHANGE_REQ_TASK = 'CHANGE_REQ_TASK',
  TCM_REMOVE_TASK = 'TCM_REMOVE_TASK',
  TCM_ALARM_SET = 'TCM_ALARM_SET',

  // web to redis
  TCM_ALARM_CLEAR = 'TCM_ALARM_CLEAR',

  // redis to web
  TCS_ALARM_CLEAR = 'TCS_ALARM_CLEAR',
  TSC_CARRIER_INSTALLED = 'TSC_CARRIER_INSTALLED',

  // Transfer
  TASK_COMMAND_PAUSE = 'TASK_COMMAND_PAUSE',
  TASK_COMMAND_RESUME = 'TASK_COMMAND_RESUME',
  TASK_COMMAND_ABORT = 'TASK_COMMAND_ABORT',
  TASK_COMMAND_RECOVERY = 'TASK_COMMAND_RECOVERY',
  HIM_FORCE_INSTALL_CARRIER = 'HIM_FORCE_INSTALL_CARRIER',

  // REDIS_ACTION
  REDIS_CONNECT = 'REDIS_CONNECT',
  REDIS_CONNECTING = 'REDIS_CONNECTING',
  REDIS_CONNECTED = 'REDIS_CONNECTED',
  REDIS_DISCONNECT = 'REDIS_DISCONNECT',
  REDIS_DISCONNECTED = 'REDIS_DISCONNECTED',
  REDIS_RESET = 'REDIS_RESET',

  USER_LOGIN_SUCESS = 'USER_LOGIN_SUCESS',
  USER_LOGOUT = 'USER_LOGOUT',
  // MODULE STATE
  MODULE_STATE_CONNECT_HIM = 'MODULE_STATE_CONNECT_HIM',
  MODULE_STATE_DISCONNECT_HIM = 'MODULE_STATE_DISCONNECT_HIM',
  MODULE_STATE_CONNECT_DCM = 'MODULE_STATE_CONNECT_DCM',
  MODULE_STATE_DISCONNECT_DCM = 'MODULE_STATE_DISCONNECT_DCM',
  MODULE_STATE_CONNECT_TCM = 'MODULE_STATE_CONNECT_TCM',
  MODULE_STATE_DISCONNECT_TCM = 'MODULE_STATE_DISCONNECT_TCM',

  MODULE_START_HIM = 'MODULE_START_HIM',
  MODULE_STOP_HIM = 'MODULE_STOP_HIM',
  MODULE_START_DCM = 'MODULE_START_DCM',
  MODULE_STOP_DCM = 'MODULE_STOP_DCM',
  MODULE_START_TCM = 'MODULE_START_TCM',
  MODULE_STOP_TCM = 'MODULE_STOP_TCM',

  MODULE_RESTART_HIM = 'MODULE_RESTART_HIM',
  MODULE_RESTART_DCM = 'MODULE_RESTART_DCM',
  MODULE_RESTART_TCM = 'MODULE_RESTART_TCM',

  MODULE_RELOAD_HIM = 'MODULE_RELOAD_HIM',
  MODULE_RELOAD_DCM = 'MODULE_RELOAD_DCM',
  MODULE_RELOAD_TCM = 'MODULE_RELOAD_TCM',

  REGISTER_REQUEST = 'USERS_REGISTER_REQUEST',
  REGISTER_SUCCESS = 'USERS_REGISTER_SUCCESS',
  REGISTER_FAILURE = 'USERS_REGISTER_FAILURE',

  LOGIN_REQUEST = 'USERS_LOGIN_REQUEST',
  LOGIN_SUCCESS = 'USERS_LOGIN_SUCCESS',
  LOGIN_FAILURE = 'USERS_LOGIN_FAILURE',

  LOGOUT = 'USERS_LOGOUT',

  GETALL_REQUEST = 'USERS_GETALL_REQUEST',
  GETALL_SUCCESS = 'USERS_GETALL_SUCCESS',
  GETALL_FAILURE = 'USERS_GETALL_FAILURE',

  DELETE_REQUEST = 'USERS_DELETE_REQUEST',
  DELETE_SUCCESS = 'USERS_DELETE_SUCCESS',
  DELETE_FAILURE = 'USERS_DELETE_FAILURE',

  EQUIPMENT_STATE_CHANGE_COMM_DISABLE = 'EQUIPMENT_STATE_CHANGE_COMM_DISABLE',
  EQUIPMENT_STATE_CHANGE_COMM_ENABLE = 'EQUIPMENT_STATE_CHANGE_COMM_ENABLE',
  EQUIPMENT_STATE_CHANGE_CONTROL_OFFLINE = 'EQUIPMENT_STATE_CHANGE_CONTROL_OFFLINE',
  EQUIPMENT_STATE_CHANGE_CONTROL_ONLINE_REMOTE = 'EQUIPMENT_STATE_CHANGE_CONTROL_ONLINE_REMOTE',
  EQUIPMENT_STATE_CHANGE_CONTROL_ONLINE_LOCAL = 'EQUIPMENT_STATE_CHANGE_CONTROL_ONLINE_LOCAL',

  EQUIPMENT_STATE_UPDATE_COMM = 'EQUIPMENT_STATE_UPDATE_COMM',
  EQUIPMENT_STATE_UPDATE_CONTROL = 'EQUIPMENT_STATE_UPDATE_CONTROL',
  EQUIPMENT_STATE_UPDATE_PROCESSING = 'EQUIPMENT_STATE_UPDATE_PROCESSING',
  EQUIPMENT_STATE_UPDATE_MULTI_COMM = 'EQUIPMENT_STATE_UPDATE_MULTI_COMM',
  EQUIPMENT_STATE_UPDATE_MULTI_CONTROL = 'EQUIPMENT_STATE_UPDATE_MULTI_CONTROL',
  EQUIPMENT_STATE_UPDATE_MULTI_PROCESSING = 'EQUIPMENT_STATE_UPDATE_MULTI_PROCESSING',
  EQUIPMENT_VALUE_UPDATE = 'EQUIPMENT_VALUE_UPDATE',
  EQUIPMENT_VALUE_UPDATE_NAME = 'EQUIPMENT_VALUE_UPDATE_NAME',
  EQUIPMENT_VALUE_UPDATE_MODEL = 'EQUIPMENT_VALUE_UPDATE_MODEL',

  /** AirShower */
  UPDATE_TCM_LIST_HAS_AIR_SHOWER = 'UPDATE_TCM_LIST_HAS_AIR_SHOWER',
  START_AIR_SHOWER = 'START_AIR_SHOWER',
  STOP_AIR_SHOWER = 'STOP_AIR_SHOWER',
  CHANGE_AIR_SHOWER_UNIT_COUNT = 'CHANGE_AIR_SHOWER_UNIT_COUNT',

  //MOTOR PARAMETER CHANGE
  CHANGE_EACH_MOTION_PARAM_SELECTED_ZONE = 'CHANGE_EACH_MOTION_PARAM_SELECTED_ZONE',
  CHANGE_EVERY_MOTION_PARAM_SELECTED_ZONE = 'CHANGE_EVERY_MOTION_PARAM_SELECTED_ZONE',
  CHANGE_EVERY_MOTION_PARAM_SAMETYPE_ZONES = 'CHANGE_EVERY_MOTION_PARAM_SAMETYPE_ZONES',
  CHANGE_EVERY_MOTION_PARAM_ALL_ZONES = 'CHANGE_EVERY_MOTION_PARAM_ALL_ZONES',

  CHANGE_OFFSET_MOVE_RELATIVE_QS = 'CHANGE_OFFSET_MOVE_RELATIVE_QS',
  CHANGE_OFFSET_SELECTED_QS = 'CHANGE_OFFSET_SELECTED_QS',
  CHANGE_STAYING_CARRIER_TIMEOUT = 'CHANGE_STAYING_CARRIER_TIMEOUT',
  ADD_TCM = 'ADD_TCM',
  RESOURCE_INFO = 'RESOURCE_INFO',
  UPDATE_RESOURCE_STATE = 'UPDATE_RESOURCE_STATE',
  CHANGE_ACTIVE_TAB = 'CHANGE_ACTIVE_TAB',
  ANY_OTHER_ACTION = 'ANY_OTHER_ACTION_SUCCESS',

  ADD_LOG_EVENT = 'ADD_LOG_EVENT',
  ADD_WARINING = 'ADD_WARINING',
  CLEAR_WARNING = 'CLEAR_WARNING',
  CLEAR_WARNING_ALL = 'CLEAR_WARNING_ALL',
  SHOW_ERROR = 'SHOW_ERROR',
  CLEAR_ERROR = 'CLEAR_ERROR',

  //GUI
  UPDATE_USE_REALPOSITION = 'UPDATE_USE_REALPOSITION',
  ALARM_SOUND_MUTE = 'ALARM_SOUND_MUTE',
  ALARM_SOUND_ON = 'ALARM_SOUND_ON',
  ALARM_SOUND_PAUSE = 'ALARM_SOUND_PAUSE',
  ALARM_SOUND_RESUME = 'ALARM_SOUND_RESUME',

  //function test
  READ_RFID = 'READ_RFID',

  //signal tower
  TURN_OFF_SIGNAL_TOWER = 'TURN_OFF_SIGNAL_TOWER',
}
