export enum ZoneType {
    TYPE_LD = 0,
    TYPE_LD_NORMAL = TYPE_LD,
    TYPE_LD_INCLUDED,
    TYPE_LD_INPUT,
    TYPE_LD_OUTPUT,
    TYPE_QS,
    TYPE_LIFTER,
    TYPE_CURVE,
    TYPE_LD_LENGTH_1000,
    TYPE_LD_LENGTH_2000,
    TYPE_PURGE_N2,
    TYPE_LIFTER_SINGLE,
    TYPE_LD_IO,
    TYPE_COUNTS,

    TYPE_IDLER = 100,
    TYPE_CCTV = 101,
}

export enum LogicalType {
    LOGICAL_TYPE_NONE = 0,
    LOGICAL_TYPE_VIRTUAL_PORT,
    LOGICAL_TYPE_GROUP_PORT,
    LOGICAL_TYPE_LOOP_PORT,
}
